### PR TITLE
Remove support for PHP 8.0, add support for PHP 8.3

### PR DESCRIPTION
**Pull request by gsteel**

### CODE REVIEW

**Comment by gsteel** [comment]
Needs a release of https://github.com/laminas/laminas-stdlib/milestone/46

**Comment by Ocramius** [comment]
I think a dependency bump is needed here, not just the related milestone release

**Comment by gsteel** [comment]
I've bumped @Ocramius, but composer would have installed 3.18 with PHP 8.3 on deps lowest anyway right?

**Comment by gsteel** [comment]
This either needs --ignore-platform-reqs or `laminas-config` will need 8.3 support

**Comment by Ocramius** [comment]
> I've bumped @Ocramius, but composer would have installed 3.18 with PHP 8.3 on deps lowest anyway right?

yep

**Review by Ocramius — APPROVED** [review]
Thanks @gsteel!

**Pull request merged**
